export enum MessageType{
    JOIN_ROOM = "JOIN_ROOM",
    SEND_MESSAGE = "SEND_MESSAGE",
    RECEIVE_MESSAGE = "RECEIVE_MESSAGE",
    ROOM_JOINED = "ROOM_JOINED",
    INVALID_ROOM = "INVALID_ROOM",
    MISSING_PARAMS = "MISSING_PARAMS",
    INVALID_MESSAGE_FORMAT = "INVALID_MESSAGE_FORMAT",
    UNKNOWN_ERROR = "UNKNOWN_ERROR",
    UNAUTHORIZED = "UNAUTHORIZED"
}